In [12]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset

In [7]:
prob = 0.5
dropout = nn.Dropout(p=prob)
x = torch.ones(10)

y = dropout(x)

print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 2., 0., 0., 0., 0., 2., 2., 0., 0.])
tensor(0.6000)


Dropout is turned off during evaluation

In [8]:
dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


Unexpectedly, turning our model's eval mode on does not affect the dropout function in the functional module

In [9]:
dropout.eval()
y = F.dropout(x)
print(y)

tensor([2., 0., 0., 2., 0., 2., 0., 0., 2., 2.])


But we can turn it on by setting the `training` parameter to **False**

In [10]:
y = F.dropout(x, training=False)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


Below cell proves that you have to remember to turn training mode on to turn on dropout

In [11]:
dropout.train()
y = dropout(x)
print(y)

dropout.eval()
y = dropout(x)
print(y)

y = dropout(x)
print(y)

tensor([2., 0., 0., 0., 2., 0., 2., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
